name = "tb-recipe-core"
main = "index.js"
compatibility_date = "2024-10-01"

[ai]
binding = "AI"

[vars]
ENV = "production"
BUILT_AT = "manual"

workers_dev = true

[env.production]
name = "tb-recipe-core"
[env.production.ai]
binding = "AI"
[env.production.vars]
ENV = "production"
BUILT_AT = "manual"
workers_dev = true
