name = "tb-allergen-organs"
main = "index.js"
compatibility_date = "2024-10-01"

usage_model = "bundled"
workers_dev = false

[vars]
ENV = "dev"
BUILT_AT = "manual"

[env.production]
workers_dev = false
usage_model = "bundled"
ENV = "production"
BUILT_AT = "manual"

[env.production.vars]
ENV = "production"
WORKER_NAME = "tb-allergen-organs-production"
LEXICON_API_URL = "https://tummy-lexicon-api.onrender.com"
